# shellcheck shell=sh
#
# PmRails core library functions.
# This file is intended to be sourced, not executed directly.

readonly _PMRAILS_GEM_HOME="/gem-home"
readonly _PMRAILS_VAR_DIR=".pmrails/var"
readonly _PMRAILS_COMPOSE_OVERRIDE_FILE=".pmrails/var/compose.override.yaml"

# Resolves PMRAILS_RUBY_VERSION based on priority rules.
#
# Resolution priority:
#   1. Preserved if PMRAILS_RUBY_VERSION is already non-empty.
#   2. "latest" if .ruby-version does not exist in the current directory.
#   3. Extracted from the first line of the .ruby-version file. The first
#      substring matching a numeric "major.minor.patch" format is used,
#      ignoring any surrounding text (e.g., extracting "3.2.2" from
#      "ruby-3.2.2").
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read/Modified.
# Outputs:
#   Writes an error message to STDERR if version parsing fails.
# Returns:
#   0: On success.
#   Does not return (exits with status 1):
#     If .ruby-version exists but no valid version can be parsed.
pmrails_resolve_ruby_version() {
    if [ -n "${PMRAILS_RUBY_VERSION:-}" ]; then
        return 0
    fi
    if ! [ -e .ruby-version ]; then
        PMRAILS_RUBY_VERSION="latest"
        return 0
    fi
    PMRAILS_RUBY_VERSION=$(sed -n '1s/^[^0-9]*\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*$/\1/p' .ruby-version)
    if [ -z "${PMRAILS_RUBY_VERSION}" ]; then
        printf '%s\n' 'pmrails: error: could not parse a version (major.minor.patch) from .ruby-version' >&2
        printf 'pmrails: .ruby-version first line: "%s"\n' "$(sed -n '1p' .ruby-version)" >&2
        exit 1
    fi
}

# Resolves PMRAILS_IMAGE_REPO based on priority rules.
#
# Resolution priority:
#   1. Preserved if PMRAILS_IMAGE_REPO is already non-empty.
#   2. "pmrails-${PMRAILS_PROJECT_NAME}" if the file specified by
#      PMRAILS_DOCKERFILE exists.
#   3. "ruby" as a fallback.
#
# Globals:
#   PMRAILS_IMAGE_REPO - Read/Modified.
#   PMRAILS_DOCKERFILE - Read. Must be set. An empty string is
#       treated as non-existent.
#   PMRAILS_PROJECT_NAME - Read. Must be set.
# Returns:
#   0: Always succeeds.
pmrails_resolve_image_repo() {
    if [ -n "${PMRAILS_IMAGE_REPO:-}" ]; then
        return 0
    fi
    if [ -e "${PMRAILS_DOCKERFILE}" ]; then
        PMRAILS_IMAGE_REPO="pmrails-${PMRAILS_PROJECT_NAME}"
    else
        PMRAILS_IMAGE_REPO="ruby"
    fi
}

# Captures all PMRAILS_* environment variables as a shell-evaluable snapshot.
#
# Intended to be paired with pmrails_restore_env.
#
# Globals:
#   PMRAILS_* - Read. All variables matching this prefix are captured.
#   _PMRAILS_ENV_SNAPSHOT - Modified (Set to the generated snapshot string).
# Returns:
#   0: Always succeeds.
pmrails_snapshot_env() {
    # gsub() escapes single quotes: ' -> '\''
    _PMRAILS_ENV_SNAPSHOT=$(awk -v sq="'" 'BEGIN {
        for (name in ENVIRON) {
            if (name ~ /^PMRAILS_/) {
                val = ENVIRON[name]
                gsub(sq, sq "\\" sq sq, val)
                printf "export %s=%s%s%s\n", name, sq, val, sq
            }
        }
    }')
}

# Restores PMRAILS_* variables from the snapshot created by pmrails_snapshot_env.
#
# Intended to be paired with pmrails_snapshot_env.
# This function MUST be called only with a snapshot generated by
# pmrails_snapshot_env in the same process to ensure security and predictable
# behavior.
#
# Globals:
#   _PMRAILS_ENV_SNAPSHOT - Read, then unset (Cleaned up after evaluation).
#   PMRAILS_* - Modified. Restored to their originally snapshotted values.
# Returns:
#   0: Always succeeds.
pmrails_restore_env() {
    eval "${_PMRAILS_ENV_SNAPSHOT}"
    unset _PMRAILS_ENV_SNAPSHOT
}

# Returns success when a PmRails configuration value is ":AUTO".
#
# Values beginning with ":" other than ":AUTO" are reserved. If such a value
# is passed, this function immediately aborts the script with an error.
#
# Arguments:
#   $1 - Configuration value to classify.
# Outputs:
#   Writes an error message to STDERR for unsupported reserved values.
# Returns:
#   0: The value is ":AUTO".
#   1: The value is a normal literal configuration value.
#   Does not return (exits with status 1):
#     If the value starts with ":" but is not a supported command.
pmrails_is_auto_config_value() {
    case "$1" in
    ':AUTO')
        return 0
        ;;
    :*)
        printf 'pmrails: error: unsupported reserved PMRAILS configuration value: "%s"\n' "$1" >&2
        exit 1
        ;;
    *)
        return 1
        ;;
    esac
}

# Unsets PmRails runtime configuration variables that are set to ":AUTO".
#
# Variables set to the ":AUTO" command-like value are unset so that subsequent
# dynamic-default resolution can populate them. Other values beginning with ":"
# are reserved and rejected early.
#
# PMRAILS_SYS_CONF is intentionally excluded because it controls where
# configuration is loaded from, rather than being part of the runtime
# configuration itself.
#
# Globals:
#   PMRAILS_* - Read/Modified for known PmRails configuration variables.
# Returns:
#   0: On success.
#   Does not return (exits with status 1):
#     If any known configuration variable contains an unsupported reserved
#     value.
pmrails_unset_auto_config_variables() {
    # Unset values are passed to the classifier as empty strings. Empty strings
    # are normal literal values, not reserved commands, so this preserves the
    # distinction between unset, empty, and ":AUTO" without extra set checks.
    if pmrails_is_auto_config_value "${PMRAILS_RUBY_VERSION:-}"; then
        unset PMRAILS_RUBY_VERSION
    fi
    if pmrails_is_auto_config_value "${PMRAILS_RUBY_VERSION_SUFFIX:-}"; then
        unset PMRAILS_RUBY_VERSION_SUFFIX
    fi
    if pmrails_is_auto_config_value "${PMRAILS_RUBY_VERSION_AT_NEW:-}"; then
        unset PMRAILS_RUBY_VERSION_AT_NEW
    fi
    if pmrails_is_auto_config_value "${PMRAILS_PORTS:-}"; then
        unset PMRAILS_PORTS
    fi
    if pmrails_is_auto_config_value "${PMRAILS_PROJECT_NAME:-}"; then
        unset PMRAILS_PROJECT_NAME
    fi
    if pmrails_is_auto_config_value "${PMRAILS_DOCKERFILE:-}"; then
        unset PMRAILS_DOCKERFILE
    fi
    if pmrails_is_auto_config_value "${PMRAILS_BUILD_CONTEXT:-}"; then
        unset PMRAILS_BUILD_CONTEXT
    fi
    if pmrails_is_auto_config_value "${PMRAILS_COMPOSE_FILE:-}"; then
        unset PMRAILS_COMPOSE_FILE
    fi
    if pmrails_is_auto_config_value "${PMRAILS_GEM_HOME_ABI:-}"; then
        unset PMRAILS_GEM_HOME_ABI
    fi
    if pmrails_is_auto_config_value "${PMRAILS_IMAGE_REPO:-}"; then
        unset PMRAILS_IMAGE_REPO
    fi
}

# Sources PmRails configuration files from multiple scopes.
#
# Files are sourced in the following order, allowing later files to
# override settings from earlier ones:
#   1. ${PMRAILS_SYS_CONF:-/etc/pmrails/config}             (system-wide)
#   2. ${XDG_CONFIG_HOME:-${HOME:-}/.config}/pmrails/config (user)
#   3. ./.pmrails/config                                    (project)
#   4. ./.pmrails/config.local                              (project local, gitignored)
#
# Files that do not exist or are not readable are silently skipped.
#
# Warning: This function executes configuration files directly in the
# current shell environment without isolation. Use with trusted files only.
#
# Globals:
#   PMRAILS_SYS_CONF - Read. Overrides the system config path when set.
#   XDG_CONFIG_HOME - Read. Used to locate the user config directory.
#   HOME - Read. Used as a fallback if XDG_CONFIG_HOME is unset.
#   PMRAILS_* - Modified. Sourced files are expected to set or override
#       variables matching this prefix.
# Returns:
#   0: On success, assuming no sourced file triggers a fatal error or exit.
pmrails_load_config_files() {
    _pmrails_system_config_path="${PMRAILS_SYS_CONF:-/etc/pmrails/config}"
    _pmrails_user_config_path="${XDG_CONFIG_HOME:-${HOME:-}/.config}/pmrails/config"
    _pmrails_project_config_path="./.pmrails/config"
    _pmrails_local_config_path="./.pmrails/config.local"

    for _pmrails_config_path in \
        "${_pmrails_system_config_path}" \
        "${_pmrails_user_config_path}" \
        "${_pmrails_project_config_path}" \
        "${_pmrails_local_config_path}"; do
        if [ -f "${_pmrails_config_path}" ] && [ -r "${_pmrails_config_path}" ]; then
            # shellcheck disable=SC1090
            . "${_pmrails_config_path}"
        fi
    done

    unset \
        _pmrails_system_config_path \
        _pmrails_user_config_path \
        _pmrails_project_config_path \
        _pmrails_local_config_path \
        _pmrails_config_path
}

# Fills in PMRAILS_* variables that are not yet set, using runtime-derived defaults.
#
# Most variables are set if unset or empty, ensuring idempotency.
# Intended to be called after other variable setting functions so that user-set
# values and config file values take precedence over these defaults.
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read/Modified. Resolved by pmrails_resolve_ruby_version.
#   PMRAILS_DOCKERFILE - Read/Modified.
#   PMRAILS_BUILD_CONTEXT - Read/Modified.
#   PMRAILS_PROJECT_NAME - Read/Modified. Defaults to a sanitized, truncated
#       form of the current directory name.
#   PMRAILS_IMAGE_REPO - Read/Modified. Resolved by pmrails_resolve_image_repo.
#   PMRAILS_RUBY_VERSION_SUFFIX - Read/Modified.
#   PMRAILS_RUBY_VERSION_AT_NEW - Read/Modified.
#   PMRAILS_PORTS - Read/Modified.
#   PMRAILS_COMPOSE_FILE - Read/Modified.
#   PWD - Read. Must be set. Used to derive PMRAILS_PROJECT_NAME.
# Returns:
#   0: On success.
#   Does not return (exits with status 1): If PMRAILS_PROJECT_NAME is resolved
#       to empty, if PWD is unset or empty, or if .ruby-version exists but no
#       valid version can be parsed (propagated from
#       pmrails_resolve_ruby_version).
pmrails_fill_dynamic_defaults() {
    pmrails_resolve_ruby_version
    PMRAILS_DOCKERFILE=${PMRAILS_DOCKERFILE:-'.pmrails/Dockerfile'}
    PMRAILS_BUILD_CONTEXT=${PMRAILS_BUILD_CONTEXT:-'.pmrails/build_context'}
    if [ -z "${PWD:-}" ]; then
        printf '%s\n' 'pmrails: error: PWD can not be unset nor empty' >&2
        exit 1
    fi
    # shellcheck disable=SC2018,SC2019
    PMRAILS_PROJECT_NAME=${PMRAILS_PROJECT_NAME:-"$(
        export LC_ALL=C
        basename "${PWD}" | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9]/_/g; s/_\{2,\}/_/g; s/^_//' | cut -c 1-16 | sed 's/_*$//'
    )"}
    if [ -z "${PMRAILS_PROJECT_NAME}" ]; then
        printf '%s\n' 'pmrails: error: PMRAILS_PROJECT_NAME can not be empty' >&2
        exit 1
    fi
    pmrails_resolve_image_repo
    PMRAILS_RUBY_VERSION_SUFFIX=${PMRAILS_RUBY_VERSION_SUFFIX:-}
    PMRAILS_RUBY_VERSION_AT_NEW=${PMRAILS_RUBY_VERSION_AT_NEW:-'latest'}
    if [ -z "${PMRAILS_PORTS+x}" ]; then
        PMRAILS_PORTS='127.0.0.1:3000:3000'
    fi
    PMRAILS_COMPOSE_FILE=${PMRAILS_COMPOSE_FILE:-'.pmrails/compose.yaml'}
}

# Prepares the current shell with a complete pmrails runtime configuration.
#
# Intended to be called once by executable shell scripts in bin/ before they
# invoke other pmrails_* helpers. It guarantees that the required PMRAILS_*
# variables are fully resolved and available in the current shell.
#
# Variables are populated with the following precedence (highest first):
#   1. Caller-exported PMRAILS_* environment variables.
#   2. Configuration files sourced by pmrails_load_config_files.
#   3. Runtime-derived defaults from pmrails_fill_dynamic_defaults.
#
# In the final effective runtime configuration, ":AUTO" has the same effect as
# leaving the variable undefined. Any other runtime configuration value
# beginning with ":" is reserved and rejected before defaults are resolved.
#
# On success, entrypoint scripts can rely on at least the following variables
# being ready for use:
#   PMRAILS_RUBY_VERSION
#   PMRAILS_RUBY_VERSION_SUFFIX
#   PMRAILS_IMAGE_REPO
#   PMRAILS_RUBY_VERSION_AT_NEW
#   PMRAILS_PORTS
#   PMRAILS_PROJECT_NAME
#   PMRAILS_DOCKERFILE
#   PMRAILS_BUILD_CONTEXT
#   PMRAILS_COMPOSE_FILE
#
# Globals:
#   PMRAILS_* - Read/Modified. Resolved according to the precedence rules.
#   _PMRAILS_ENV_SNAPSHOT - Modified transiently during setup, then unset.
# Returns:
#   0: On success.
#   Does not return (exits with status 1): Propagates fatal errors from
#       underlying resolution functions if prerequisites are unmet or parsing
#       fails.
pmrails_setup() {
    pmrails_snapshot_env
    pmrails_load_config_files
    pmrails_restore_env
    pmrails_unset_auto_config_variables
    pmrails_fill_dynamic_defaults
}

# Ensures the in-project HOME directory exists.
#
# Globals:
#   _PMRAILS_VAR_DIR - Read. Parent directory of the HOME directory.
# Returns:
#   0: On success.
#   Non-zero: Propagates the exit status of "mkdir -p" on failure.
pmrails_ensure_home_dir() {
    mkdir -p "${_PMRAILS_VAR_DIR}/home"
}

# Resolves the container image tag and name used by PmRails runtime commands.
#
# Globals:
#   PMRAILS_IMAGE_REPO - Read. Must be set.
#   PMRAILS_RUBY_VERSION - Read. Must be set.
#   PMRAILS_RUBY_VERSION_SUFFIX - Read. Must be set. Empty or a Ruby image tag
#       suffix fragment including its leading separator, such as "-bookworm".
#   _PMRAILS_IMAGE_TAG - Modified.
#   _PMRAILS_IMAGE_NAME - Modified. Always set to "<repo>:<tag>".
# Returns:
#   0: Always succeeds.
pmrails_resolve_image() {
    _PMRAILS_IMAGE_TAG="${PMRAILS_RUBY_VERSION}${PMRAILS_RUBY_VERSION_SUFFIX}"
    _PMRAILS_IMAGE_NAME="${PMRAILS_IMAGE_REPO}:${_PMRAILS_IMAGE_TAG}"
}

# Builds the resolved project-specific container image.
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read. Passed as a build argument.
#   PMRAILS_RUBY_VERSION_SUFFIX - Read. Passed as a build argument.
#   PMRAILS_DOCKERFILE - Read. Used as the Dockerfile path for podman build.
#   PMRAILS_BUILD_CONTEXT - Read. Used as the podman build context.
#   _PMRAILS_IMAGE_NAME - Read. Must be resolved before calling.
# Returns:
#   0: Image was successfully built.
#   Non-zero: Propagates the exit status of "podman build" on failure.
pmrails_build_image() {
    mkdir -p "${PMRAILS_BUILD_CONTEXT}"
    podman build \
        --build-arg PMRAILS_RUBY_VERSION="${PMRAILS_RUBY_VERSION}" \
        --build-arg PMRAILS_RUBY_VERSION_SUFFIX="${PMRAILS_RUBY_VERSION_SUFFIX}" \
        -t "${_PMRAILS_IMAGE_NAME}" \
        -f "${PMRAILS_DOCKERFILE}" \
        "${PMRAILS_BUILD_CONTEXT}"
}

# Ensures that the container image "<repo>:<tag>" exists locally.
#
#   - If PMRAILS_IMAGE_REPO is "ruby", podman is not invoked at all. The
#     upstream ruby image is left to be pulled on demand by a later
#     podman run.
#   - Otherwise, "podman image exists" is queried, and "podman build" is
#     invoked only when the image is missing.
#
# Globals:
#   PMRAILS_IMAGE_REPO - Read. Must be set.
#   _PMRAILS_IMAGE_TAG - Modified indirectly via pmrails_resolve_image.
#   _PMRAILS_IMAGE_NAME - Modified indirectly via pmrails_resolve_image.
# Returns:
#   0: Image exists or was successfully built.
#   Non-zero: Propagates the exit status of "podman build" on failure.
pmrails_ensure_image() {
    pmrails_resolve_image
    if [ "ruby" != "${PMRAILS_IMAGE_REPO}" ] && ! podman image exists "${_PMRAILS_IMAGE_NAME}"; then
        pmrails_build_image
    fi
}

# Resolves the upstream Ruby image used for project creation commands.
#
# This does not check, pull, or build the image. The upstream ruby image is left
# to be pulled on demand by a later podman run.
#
# Globals:
#   PMRAILS_RUBY_VERSION_AT_NEW - Read. Selects the upstream ruby image tag.
#   _PMRAILS_IMAGE_TAG - Modified. Set to PMRAILS_RUBY_VERSION_AT_NEW.
#   _PMRAILS_IMAGE_NAME - Modified. Set to "ruby:<tag>".
# Returns:
#   0: Always succeeds.
pmrails_resolve_image_for_new() {
    _PMRAILS_IMAGE_TAG="${PMRAILS_RUBY_VERSION_AT_NEW}"
    _PMRAILS_IMAGE_NAME="ruby:${_PMRAILS_IMAGE_TAG}"
}

# Resolves the Ruby version used to namespace the shared GEM_HOME volume.
#
# If the image tag begins with a major.minor.patch Ruby version, that version
# is used without invoking podman. Otherwise, a one-shot container is run to
# print the image's actual RUBY_VERSION.
#
# Arguments:
#   $1 - Image tag to use as a Ruby-version hint.
#   $2 - Image name to run when the tag does not contain a full Ruby version.
# Outputs:
#   Writes the resolved Ruby version to STDOUT.
pmrails_resolve_volume_ruby_version() {
    _pmrails_image_tag="$1"
    _pmrails_image_name="$2"

    _pmrails_volume_ruby_version=$(printf "%s\n" "${_pmrails_image_tag}" | sed -n '1s/^\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*$/\1/p')
    if [ -z "${_pmrails_volume_ruby_version}" ]; then
        _pmrails_volume_ruby_version=$(podman run --rm "${_pmrails_image_name}" ruby -e 'puts RUBY_VERSION') || exit $?
    fi
    printf "%s\n" "${_pmrails_volume_ruby_version}"

    unset _pmrails_image_tag _pmrails_image_name _pmrails_volume_ruby_version
}

# Resolves PMRAILS_GEM_HOME_ABI for the selected image tag.
#
# Resolution rules:
#   1. If PMRAILS_GEM_HOME_ABI is set, preserve it verbatim. An empty
#      string is meaningful and disables the compatibility suffix.
#   2. If PMRAILS_GEM_HOME_ABI is unset and _PMRAILS_IMAGE_TAG is "latest",
#      set PMRAILS_GEM_HOME_ABI to an empty string to avoid using "latest"
#      as a compatibility key.
#   3. If PMRAILS_GEM_HOME_ABI is unset and _PMRAILS_IMAGE_TAG is not
#      "latest", derive the key by removing a leading numeric Ruby-version
#      prefix and one optional following "-". It removes at most a
#      major[.minor[.patch]] prefix, leaving extra version-like text and other
#      separators in the ABI suffix to avoid merging incompatible gem stores.
#      For example, "4.0-trixie" becomes "trixie", and
#      "4.0.3-slim-trixie" becomes "slim-trixie".
#
# Globals:
#   PMRAILS_GEM_HOME_ABI - Read/Modified.
#   _PMRAILS_IMAGE_TAG - Read when PMRAILS_GEM_HOME_ABI is unset.
# Returns:
#   0: Always succeeds.
pmrails_resolve_gem_home_abi() {
    if [ -z "${PMRAILS_GEM_HOME_ABI+x}" ]; then
        if [ "${_PMRAILS_IMAGE_TAG}" = "latest" ]; then
            PMRAILS_GEM_HOME_ABI=""
        else
            PMRAILS_GEM_HOME_ABI=$(printf "%s\n" "${_PMRAILS_IMAGE_TAG}" | sed 's/^[0-9]\{1,\}\(\.[0-9]\{1,\}\)\{0,2\}-\{0,1\}//')
        fi
    fi
}

# Ensures that the shared GEM_HOME volume for the selected image exists.
#
# The volume name is built from:
#   1. The image's major.minor.patch Ruby version
#   2. The optional GEM_HOME ABI suffix
#
# Globals:
#   PMRAILS_GEM_HOME_ABI - Read/Modified indirectly via
#       pmrails_resolve_gem_home_abi.
#   _PMRAILS_IMAGE_TAG - Read. Used as a Ruby-version hint and ABI suffix
#       source.
#   _PMRAILS_IMAGE_NAME - Read. Used to query RUBY_VERSION when the tag does
#       not include a major.minor.patch version.
#   _PMRAILS_VOLUME_NAME - Modified. Set to the created volume name.
# Returns:
#   0: Volume exists or was created.
pmrails_ensure_volume() {
    pmrails_resolve_gem_home_abi
    _pmrails_volume_ruby_version=$(pmrails_resolve_volume_ruby_version "${_PMRAILS_IMAGE_TAG}" "${_PMRAILS_IMAGE_NAME}") || exit $?

    _PMRAILS_VOLUME_NAME="pmrails-gem_home-${_pmrails_volume_ruby_version}"
    if [ -n "${PMRAILS_GEM_HOME_ABI}" ]; then
        _PMRAILS_VOLUME_NAME="${_PMRAILS_VOLUME_NAME}-${PMRAILS_GEM_HOME_ABI}"
    fi
    podman volume create --ignore "${_PMRAILS_VOLUME_NAME}" >/dev/null

    unset _pmrails_volume_ruby_version
}

# Generates a Compose override YAML file for port binding configuration from
# PMRAILS_PORTS.
#
# Writes to the path specified by _PMRAILS_COMPOSE_OVERRIDE_FILE.
#   - If PMRAILS_PORTS is unset, empty, or whitespace-only, writes a minimal
#     "services: {}" placeholder that satisfies Compose validation with no port
#     bindings.
#   - Otherwise: writes a rails-app service block with each whitespace-separated
#     token in PMRAILS_PORTS as a separate port entry, using IFS word splitting.
#     Tokens are passed through unvalidated.
#
# Globals:
#   PMRAILS_PORTS - Read. Whitespace-separated port mappings.
#   _PMRAILS_COMPOSE_OVERRIDE_FILE - Read. The target file path to be
#       created or overwritten.
# Returns:
#   0: Always succeeds.
pmrails_generate_compose_override() {
    (
        set -f
        # shellcheck disable=SC2086
        set -- ${PMRAILS_PORTS:-}
        if [ $# -eq 0 ]; then
            printf 'services: {}\n'
        else
            # editorconfig-checker-disable
            cat <<'EOF'
services:
  rails-app:
    ports:
EOF
            # editorconfig-checker-enable
            for port in "$@"; do
                printf '      - "%s"\n' "${port}"
            done
        fi
    ) >"${_PMRAILS_COMPOSE_OVERRIDE_FILE}"
}

# Runs podman-compose with the layered Compose configuration.
#
# Generates the port-binding override file via pmrails_generate_compose_override
# before invoking podman-compose.
#
# Compose files are applied in the following order (later overrides earlier):
#   1. Built-in base:
#        "$_PMRAILS_SCRIPT_DIR/../share/compose.base.yaml"
#   2. Generated override:
#        "$_PMRAILS_COMPOSE_OVERRIDE_FILE"
#   3. User/project config:
#        "$PMRAILS_COMPOSE_FILE"
#
# Selected variables are injected into podman-compose's environment via "env"
# for use in Compose variable interpolation.
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read. Exported to compose environment.
#   PMRAILS_PROJECT_NAME - Read. Exported to compose environment and
#       passed to podman-compose via the -p flag.
#   PMRAILS_COMPOSE_FILE - Read. Path to the user/project-specific compose file.
#   _PMRAILS_GEM_HOME - Read. Exported for the shared GEM_HOME mount.
#   _PMRAILS_VOLUME_NAME - Read. Exported for the external shared GEM_HOME
#       volume.
#   _PMRAILS_VAR_DIR - Read. Exported to compose environment.
#   _PMRAILS_IMAGE_NAME - Read. Exported to compose environment.
#   _PMRAILS_SCRIPT_DIR - Read. Used to locate the built-in base compose file
#       and exported for the PmRails entrypoint mount.
#   _PMRAILS_COMPOSE_OVERRIDE_FILE - Read. Generated override file path.
# Arguments:
#   $@ - Forwarded verbatim to podman-compose.
# Returns:
#   The exit status of podman-compose.
pmrails_podman_compose() {
    pmrails_generate_compose_override
    env \
        PMRAILS_RUBY_VERSION="${PMRAILS_RUBY_VERSION}" \
        PMRAILS_PROJECT_NAME="${PMRAILS_PROJECT_NAME}" \
        _PMRAILS_SCRIPT_DIR="${_PMRAILS_SCRIPT_DIR}" \
        _PMRAILS_GEM_HOME="${_PMRAILS_GEM_HOME}" \
        _PMRAILS_VOLUME_NAME="${_PMRAILS_VOLUME_NAME}" \
        _PMRAILS_VAR_DIR="${_PMRAILS_VAR_DIR}" \
        _PMRAILS_IMAGE_NAME="${_PMRAILS_IMAGE_NAME}" \
        podman-compose \
        -p "${PMRAILS_PROJECT_NAME}" \
        -f "${_PMRAILS_SCRIPT_DIR}/../share/compose.base.yaml" \
        -f "${_PMRAILS_COMPOSE_OVERRIDE_FILE}" \
        -f "${PMRAILS_COMPOSE_FILE}" \
        "$@"
}

# Returns success when a Compose-managed rails-app container exists.
#
# Stopped containers are included because applying a Dockerfile should replace
# an existing Compose Rails container before the environment is brought up.
# Podman query failures abort the script rather than being mistaken for an
# absent container.
#
# Globals:
#   PMRAILS_PROJECT_NAME - Read. Selects the Compose project.
# Returns:
#   0: At least one rails-app container exists.
#   1: No rails-app container exists.
#   Does not return: Propagates failures from "podman ps".
pmrails_compose_rails_container_exists() {
    _pmrails_rails_container_ids=$(
        podman ps -a -q \
            --filter "label=com.docker.compose.project=${PMRAILS_PROJECT_NAME}" \
            --filter "label=com.docker.compose.service=rails-app"
    ) || exit $?

    if [ -n "${_pmrails_rails_container_ids}" ]; then
        unset _pmrails_rails_container_ids
        return 0
    fi

    unset _pmrails_rails_container_ids
    return 1
}

# Applies the configured Dockerfile to the PmRails runtime environment.
#
# The project image is always rebuilt when the Dockerfile exists. If a
# Compose-managed rails-app container already exists, it is recreated from the
# rebuilt image and the Compose environment is brought up. This makes the new
# image immediately usable while avoiding creation of a new Compose environment
# for projects that currently use only pmrails-run.
#
# Globals:
#   PMRAILS_DOCKERFILE - Read. Dockerfile to apply.
#   PMRAILS_COMPOSE_FILE - Read. Existing file enables Compose reconciliation.
# Returns:
#   0: No action was needed, or the Dockerfile was successfully applied.
pmrails_apply_dockerfile() {
    if [ ! -f "${PMRAILS_DOCKERFILE}" ]; then
        printf 'pmrails: Dockerfile not found at "%s"; nothing to apply.\n' "${PMRAILS_DOCKERFILE}"
        return 0
    fi

    printf 'pmrails: building the Rails image from "%s"...\n' "${PMRAILS_DOCKERFILE}"
    pmrails_resolve_image
    pmrails_build_image

    if [ ! -f "${PMRAILS_COMPOSE_FILE}" ]; then
        return 0
    fi

    if ! pmrails_compose_rails_container_exists; then
        printf '%s\n' 'pmrails: no Compose Rails container exists; only the image was rebuilt.'
        return 0
    fi

    pmrails_ensure_volume
    pmrails_ensure_home_dir

    printf '%s\n' 'pmrails: recreating the Compose Rails container...'
    pmrails_podman_compose up --force-recreate --no-deps --no-start rails-app

    printf '%s\n' 'pmrails: starting the Compose environment...'
    pmrails_podman_compose up -d
}

# Builds podman "-p" arguments from PMRAILS_PORTS.
#
# Parses whitespace-separated tokens in PMRAILS_PORTS, using default IFS
# word splitting, to generate a single string of "-p <token>" arguments
# into _PMRAILS_PORTS_ARGS.
#
# Pathname expansion (globbing) is disabled internally to ensure tokens
# containing wildcard characters (e.g., "*") are treated literally.
#
# If PMRAILS_PORTS is unset or empty, the output is an empty string.
# Tokens are passed through unvalidated. The resulting string is intended
# to be used unquoted in the `podman run` command line.
#
# Globals:
#   PMRAILS_PORTS - Read. Unset or empty produces an empty _PMRAILS_PORTS_ARGS.
#   _PMRAILS_PORTS_ARGS - Written.
# Returns:
#   0: Always succeeds.
pmrails_build_ports_args() {
    _PMRAILS_PORTS_ARGS=$(
        _pmrails_ports_args=""
        _pmrails_port_mapping=""

        set -f
        for _pmrails_port_mapping in ${PMRAILS_PORTS:-}; do
            if [ -n "${_pmrails_ports_args}" ]; then
                _pmrails_ports_args="${_pmrails_ports_args} "
            fi
            _pmrails_ports_args="${_pmrails_ports_args}-p ${_pmrails_port_mapping}"
        done
        printf -- "%s" "${_pmrails_ports_args}"
    )
}

# Returns success when STDOUT is attached to a terminal.
#
# Intended as a small indirection point so callers can share one TTY-detection
# rule and tests can stub that rule without overriding shell builtins.
#
# Returns:
#   0: STDOUT is a TTY.
#   1: STDOUT is not a TTY.
pmrails_stdout_is_tty() {
    [ -t 1 ]
}

# Execs "podman run" with the standard pmrails container layout.
#
# Builds port arguments via pmrails_build_ports_args, checks TTY state
#  (adding -t when so), and replaces the current process with podman.
#
# The container is configured to:
#   - Bind-mount $PWD as /x and use it as the working directory.
#   - Run ephemerally (--rm) and preserve file ownership (--userns=keep-id).
#   - Route HOME and XDG_* directories to the isolated $_PMRAILS_VAR_DIR
#     within /x.
#   - Mount the shared GEM_HOME volume and set GEM_HOME to that container path.
#   - Use the PmRails entrypoint
#
# Notes: $_PMRAILS_PORTS_ARGS is expanded unquoted intentionally; it must already
#     be correctly tokenized (produced by pmrails_build_ports_args).
#
# Globals:
#   PMRAILS_PORTS - Read indirectly via pmrails_build_ports_args.
#   _PMRAILS_PORTS_ARGS - Modified by pmrails_build_ports_args, then read.
#   PWD - Read. Used as the bind-mount source.
#   _PMRAILS_GEM_HOME - Read. Container path for the shared GEM_HOME volume.
#   _PMRAILS_VAR_DIR - Read. Base path for runtime directories.
#   _PMRAILS_IMAGE_NAME - Read. Image to run.
#   _PMRAILS_SCRIPT_DIR - Read. Used to locate the PmRails entrypoint.
#   _PMRAILS_VOLUME_NAME - Read. Shared GEM_HOME volume name.
# Arguments:
#   $@ - Forwarded verbatim to podman as the container command.
# Returns:
#   Does not return: This function exec's podman, replacing the current
#       process.
pmrails_exec_podman_run() {
    pmrails_build_ports_args
    _tty_flag=""
    if pmrails_stdout_is_tty; then
        _tty_flag="-t"
    fi
    # shellcheck disable=SC2086
    exec podman run -i ${_tty_flag} --rm --userns=keep-id \
        ${_PMRAILS_PORTS_ARGS} \
        -v "${_PMRAILS_VOLUME_NAME}:${_PMRAILS_GEM_HOME}" \
        --env "GEM_HOME=${_PMRAILS_GEM_HOME}" \
        -v "${_PMRAILS_SCRIPT_DIR}/../share/entrypoint:/pmrails-entrypoint:ro,z" \
        --entrypoint /pmrails-entrypoint \
        -v "${PWD}:/x" -w /x \
        --env "HOME=/x/${_PMRAILS_VAR_DIR}/home" \
        --env "XDG_CACHE_HOME=/x/${_PMRAILS_VAR_DIR}/cache" \
        --env "XDG_CONFIG_HOME=/x/${_PMRAILS_VAR_DIR}/config" \
        --env "XDG_DATA_HOME=/x/${_PMRAILS_VAR_DIR}/share" \
        --env "XDG_STATE_HOME=/x/${_PMRAILS_VAR_DIR}/state" \
        "${_PMRAILS_IMAGE_NAME}" "$@"
}

# Expands a plain numeric Rails version into a pessimistic RubyGems requirement.
#
# PmRails treats a version made only of digits and "." separators as shorthand
# for "use the latest compatible release in this version line". Explicit
# RubyGems requirements, prerelease-like versions, and malformed dotted values
# are preserved verbatim.
#
# Arguments:
#   $1 - Rails version or RubyGems requirement.
# Outputs:
#   Writes the expanded or preserved requirement to STDOUT.
# Returns:
#   0: Always succeeds.
pmrails_expand_rails_version_requirement() {
    _pmrails_rails_version_requirement="$1"

    if printf '%s\n' "${_pmrails_rails_version_requirement}" | grep -Eq '^[0-9]+(\.[0-9]+)*$'; then
        printf '~> %s.0\n' "${_pmrails_rails_version_requirement}"
    else
        printf '%s\n' "${_pmrails_rails_version_requirement}"
    fi

    unset _pmrails_rails_version_requirement
}

# Runs "rails new" in a one-shot container to generate a new Rails project.
#
# Checks TTY state (adding -t when so) and runs podman without exec,
# so control returns to the caller after rails new exits.
#
# The function expands plain numeric Rails versions into pessimistic RubyGems
# requirements before invoking the container. The inline script installs that
# requirement into the shared GEM_HOME, extracts the actual installed Rails
# version, reports it, and runs that exact version via "rails _<version>_ new".
# The function's $1 becomes the Rails version requirement for "gem install"; the
# remaining "$@" are forwarded unchanged to "rails new".
#
# The container is configured to:
#   - Bind-mount $PWD as /x and use it as the working directory.
#   - Run ephemerally (--rm) and preserve file ownership (--userns=keep-id).
#   - Use a tmpfs HOME because project generation should not persist container
#     home state into the new project.
#   - Mount the shared GEM_HOME volume
#   - Use the PmRails entrypoint
#
# Globals:
#   PWD - Read. Used as the bind-mount source.
#   _PMRAILS_GEM_HOME - Read. Container path for the shared GEM_HOME volume.
#   _PMRAILS_IMAGE_NAME - Read. Image to run.
#   _PMRAILS_SCRIPT_DIR - Read. Used to locate the PmRails entrypoint.
#   _PMRAILS_VOLUME_NAME - Read. Shared GEM_HOME volume name.
# Arguments:
#   $1 - Rails version to install (e.g. "8.0.2").
#   $@ - Remaining arguments forwarded verbatim to "rails new".
# Returns:
#   The exit status of "podman run".
pmrails_podman_run_rails_new() {
    _pmrails_rails_version="$1"
    shift
    _pmrails_rails_version_requirement=$(pmrails_expand_rails_version_requirement "${_pmrails_rails_version}")
    if [ "${_pmrails_rails_version_requirement}" != "${_pmrails_rails_version}" ]; then
        printf 'pmrails: using Rails version requirement "%s" for "%s"\n' "${_pmrails_rails_version_requirement}" "${_pmrails_rails_version}"
    fi
    set -- "${_pmrails_rails_version_requirement}" "$@"
    unset _pmrails_rails_version _pmrails_rails_version_requirement

    _tty_flag=""
    if pmrails_stdout_is_tty; then
        _tty_flag="-t"
    fi
    # shellcheck disable=SC2086
    podman run -i ${_tty_flag} --rm --userns=keep-id \
        -v "${_PMRAILS_VOLUME_NAME}:${_PMRAILS_GEM_HOME}" \
        --env "GEM_HOME=${_PMRAILS_GEM_HOME}" \
        -v "${_PMRAILS_SCRIPT_DIR}/../share/entrypoint:/pmrails-entrypoint:ro,z" \
        --entrypoint /pmrails-entrypoint \
        -v "${PWD}:/x" -w /x \
        --tmpfs /home/pmrails --env HOME=/home/pmrails \
        "${_PMRAILS_IMAGE_NAME}" \
        sh -c '
set -eu
ver="$1"
shift
gem_out=$(gem install rails -v "${ver}") || exit $?
real_ver=$(printf "%s\n" "${gem_out}" | sed -nE "/\.gem([[:space:]]|\$)/d; s/(^|.*[[:space:]])rails-([0-9][0-9A-Za-z.]*)([[:space:]]|\$).*/\2/p" | tail -n 1)
if [ -z "${real_ver}" ]; then
    printf "pmrails: error: could not extract the installed Rails version from \"gem install rails -v %s\" output\n" "${ver}" >&2
    exit 1
fi
printf "pmrails: using Rails version %s for rails new\n" "${real_ver}"
exec rails "_${real_ver}_" new "$@"
' -- "$@"
}

# Execs "podman run" to generate PmRails configuration files in the current
# project.
#
# Checks TTY state (adding -t when so), mounts the local PmRails library into
# the container, and replaces the current process with podman.
#
# The container is configured to:
#   - Bind-mount $PWD as /x and use it as the working directory.
#   - Run ephemerally (--rm) and preserve file ownership (--userns=keep-id).
#   - Use a tmpfs HOME because initialization should not persist container home
#     state into the project.
#   - Mount the shared GEM_HOME volume
#   - Use the PmRails entrypoint
#
# Globals:
#   PWD - Read. Used as the bind-mount source.
#   _PMRAILS_GEM_HOME - Read. Container path for the shared GEM_HOME volume.
#   _PMRAILS_IMAGE_NAME - Read. Image to run.
#   _PMRAILS_SCRIPT_DIR - Read. Used to locate the PmRails library and
#       entrypoint.
#   _PMRAILS_VOLUME_NAME - Read. Shared GEM_HOME volume name.
# Arguments:
#   $@ - Forwarded verbatim to "ruby /pmrails/lib/pmrails.rb init".
# Returns:
#   Does not return: This function exec's podman, replacing the current
#       process.
pmrails_exec_podman_run_init() {
    _tty_flag=""
    if pmrails_stdout_is_tty; then
        _tty_flag="-t"
    fi
    exec podman run -i ${_tty_flag} --rm --userns=keep-id \
        -v "${_PMRAILS_VOLUME_NAME}:${_PMRAILS_GEM_HOME}" \
        --env "GEM_HOME=${_PMRAILS_GEM_HOME}" \
        -v "${_PMRAILS_SCRIPT_DIR}/../share/entrypoint:/pmrails-entrypoint:ro,z" \
        --entrypoint /pmrails-entrypoint \
        -v "${_PMRAILS_SCRIPT_DIR}/../lib:/pmrails/lib:ro,z" \
        -v "${PWD}:/x" -w /x \
        --tmpfs /home/pmrails --env HOME=/home/pmrails \
        "${_PMRAILS_IMAGE_NAME}" \
        sh -c 'gem install --conservative thor activesupport && ruby /pmrails/lib/pmrails.rb init "$@"' -- "$@"
}
