# shellcheck shell=sh
#
# PmRails core library functions.
# This file is intended to be sourced, not executed directly.

readonly _PMRAILS_VAR_DIR=".pmrails/var"
readonly _PMRAILS_COMPOSE_OVERRIDE_FILE=".pmrails/var/compose.override.yaml"

# Resolves PMRAILS_RUBY_VERSION based on priority rules.
#
# Resolution priority:
#   1. Preserved if PMRAILS_RUBY_VERSION is already non-empty.
#   2. "latest" if .ruby-version does not exist in the current directory.
#   3. Extracted from the first line of the .ruby-version file. The first
#      substring matching a numeric "major.minor.patch" format is used,
#      ignoring any surrounding text (e.g., extracting "3.2.2" from
#      "ruby-3.2.2").
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read/Modified.
# Outputs:
#   Writes an error message to STDERR if version parsing fails.
# Returns:
#   0: On success.
#   Does not return (exits with status 3):
#     If .ruby-version exists but no valid version can be parsed.
pmrails_resolve_ruby_version() {
    if [ -n "${PMRAILS_RUBY_VERSION:-}" ]; then
        return 0
    fi
    if ! [ -e .ruby-version ]; then
        PMRAILS_RUBY_VERSION="latest"
        return 0
    fi
    PMRAILS_RUBY_VERSION=$(sed -n '1s/^[^0-9]*\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*$/\1/p' .ruby-version)
    if [ -z "${PMRAILS_RUBY_VERSION}" ]; then
        printf '%s\n' 'error: could not parse a version (major.minor.patch) from .ruby-version' >&2
        printf 'first line: "%s"\n' "$(sed -n '1p' .ruby-version)" >&2
        exit 3
    fi
}

# Resolves PMRAILS_IMAGE_REPO based on priority rules.
#
# Resolution priority:
#   1. Preserved if PMRAILS_IMAGE_REPO is already non-empty.
#   2. "pmrails-${PMRAILS_PROJECT_NAME}" if the file specified by
#      PMRAILS_DOCKERFILE exists.
#   3. "ruby" as a fallback.
#
# Globals:
#   PMRAILS_IMAGE_REPO - Read/Modified.
#   PMRAILS_DOCKERFILE - Read. Must be set. An empty string is
#       treated as non-existent.
#   PMRAILS_PROJECT_NAME - Read. Must be set.
# Returns:
#   0: Always succeeds.
pmrails_resolve_image_repo() {
    if [ -n "${PMRAILS_IMAGE_REPO:-}" ]; then
        return 0
    fi
    if [ -e "${PMRAILS_DOCKERFILE}" ]; then
        PMRAILS_IMAGE_REPO="pmrails-${PMRAILS_PROJECT_NAME}"
    else
        PMRAILS_IMAGE_REPO="ruby"
    fi
}

# Captures all PMRAILS_* environment variables as a shell-evaluable snapshot.
#
# Intended to be paired with pmrails_restore_env.
#
# Globals:
#   PMRAILS_* - Read. All variables matching this prefix are captured.
#   _PMRAILS_ENV_SNAPSHOT - Modified (Set to the generated snapshot string).
# Returns:
#   0: Always succeeds.
pmrails_snapshot_env() {
    # gsub() escapes single quotes: ' -> '\''
    _PMRAILS_ENV_SNAPSHOT=$(awk -v sq="'" 'BEGIN {
        for (name in ENVIRON) {
            if (name ~ /^PMRAILS_/) {
                val = ENVIRON[name]
                gsub(sq, sq "\\" sq sq, val)
                printf "export %s=%s%s%s\n", name, sq, val, sq
            }
        }
    }')
}

# Restores PMRAILS_* variables from the snapshot created by pmrails_snapshot_env.
#
# Intended to be paired with pmrails_snapshot_env.
# This function MUST be called only with a snapshot generated by
# pmrails_snapshot_env in the same process to ensure security and predictable
# behavior.
#
# Globals:
#   _PMRAILS_ENV_SNAPSHOT - Read, then unset (Cleaned up after evaluation).
#   PMRAILS_* - Modified. Restored to their originally snapshotted values.
# Returns:
#   0: Always succeeds.
pmrails_restore_env() {
    eval "${_PMRAILS_ENV_SNAPSHOT}"
    unset _PMRAILS_ENV_SNAPSHOT
}

# Sources PmRails configuration files from multiple scopes.
#
# Files are sourced in the following order, allowing later files to
# override settings from earlier ones:
#   1. ${PMRAILS_SYS_CONF:-/etc/pmrails/config}             (system-wide)
#   2. ${XDG_CONFIG_HOME:-${HOME:-}/.config}/pmrails/config (user)
#   3. ./.pmrails/config                                    (project)
#   4. ./.pmrails/config.local                              (project local, gitignored)
#
# Files that do not exist or are not readable are silently skipped.
#
# Warning: This function executes configuration files directly in the
# current shell environment without isolation. Use with trusted files only.
#
# Globals:
#   PMRAILS_SYS_CONF - Read. Overrides the system config path when set.
#   XDG_CONFIG_HOME - Read. Used to locate the user config directory.
#   HOME - Read. Used as a fallback if XDG_CONFIG_HOME is unset.
#   PMRAILS_* - Modified. Sourced files are expected to set or override
#       variables matching this prefix.
# Returns:
#   0: On success, assuming no sourced file triggers a fatal error or exit.
pmrails_load_config_files() {
    _pmrails_system_config_path="${PMRAILS_SYS_CONF:-/etc/pmrails/config}"
    _pmrails_user_config_path="${XDG_CONFIG_HOME:-${HOME:-}/.config}/pmrails/config"
    _pmrails_project_config_path="./.pmrails/config"
    _pmrails_local_config_path="./.pmrails/config.local"

    for _pmrails_config_path in \
        "${_pmrails_system_config_path}" \
        "${_pmrails_user_config_path}" \
        "${_pmrails_project_config_path}" \
        "${_pmrails_local_config_path}"; do
        if [ -f "${_pmrails_config_path}" ] && [ -r "${_pmrails_config_path}" ]; then
            # shellcheck disable=SC1090
            . "${_pmrails_config_path}"
        fi
    done

    unset \
        _pmrails_system_config_path \
        _pmrails_user_config_path \
        _pmrails_project_config_path \
        _pmrails_local_config_path \
        _pmrails_config_path
}

# Sets hardcoded default values for PMRAILS_* configuration variables.
#
# Always overwrites existing values unconditionally. Intended to be called
# before pmrails_load_config_files so that config files can override these
# defaults, and before pmrails_restore_env so that user-set environment
# variables take final precedence.
#
# Globals:
#   PMRAILS_PORTS - Written.
# Returns:
#   0: Always succeeds.
pmrails_load_static_defaults() {
    PMRAILS_PORTS='3000:3000'
}

# Fills in PMRAILS_* variables that are not yet set, using runtime-derived defaults.
#
# Each variable is set only if it is currently unset or empty, ensuring idempotency.
# Intended to be called after other variable setting functions so that user-set
# values and config file values take precedence over these defaults.
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read/Modified. Resolved by pmrails_resolve_ruby_version.
#   PMRAILS_DOCKERFILE - Read/Modified.
#   PMRAILS_PROJECT_NAME - Read/Modified. Defaults to a sanitized, truncated
#       form of the current directory name.
#   PMRAILS_IMAGE_REPO - Read/Modified. Resolved by pmrails_resolve_image_repo.
#   PMRAILS_RUBY_VERSION_AT_NEW - Read/Modified.
#   PMRAILS_COMPOSE_FILE - Read/Modified.
#   PWD - Read. Must be set. Used to derive PMRAILS_PROJECT_NAME.
# Returns:
#   0: On success.
#   Does not return (exits with status 2): If PMRAILS_PROJECT_NAME is resolved
#       to empty or PWD is unset or empty.
#   Does not return (exits with status 3): If .ruby-version exists but
#       no valid version can be parsed. (propagated from
#       pmrails_resolve_ruby_version).
pmrails_fill_dynamic_defaults() {
    pmrails_resolve_ruby_version
    PMRAILS_DOCKERFILE=${PMRAILS_DOCKERFILE:-'.pmrails/Dockerfile'}
    if [ -z "${PWD:-}" ]; then
        printf '%s\n' 'error: PWD can not be unset nor empty' >&2
        exit 2
    fi
    PMRAILS_PROJECT_NAME=${PMRAILS_PROJECT_NAME:-"$(basename "${PWD}" | sed 's/[^a-zA-Z0-9]/_/g; s/_\{2,\}/_/g; s/^_//' | cut -c 1-16 | sed 's/[^a-zA-Z0-9]*$//')"}
    if [ -z "${PMRAILS_PROJECT_NAME}" ]; then
        printf '%s\n' 'error: PMRAILS_PROJECT_NAME can not be empty' >&2
        exit 2
    fi
    pmrails_resolve_image_repo
    PMRAILS_RUBY_VERSION_AT_NEW=${PMRAILS_RUBY_VERSION_AT_NEW:-'latest'}
    PMRAILS_COMPOSE_FILE=${PMRAILS_COMPOSE_FILE:-'.pmrails/compose.yaml'}
}

# Prepares the current shell with a complete pmrails runtime configuration.
#
# Intended to be called once by executable shell scripts in bin/ before they
# invoke other pmrails_* helpers. It guarantees that the required PMRAILS_*
# variables are fully resolved and available in the current shell.
#
# Variables are populated with the following precedence (highest first):
#   1. Caller-exported PMRAILS_* environment variables.
#   2. Configuration files sourced by pmrails_load_config_files.
#   3. Static defaults from pmrails_load_static_defaults.
#   4. Runtime-derived defaults from pmrails_fill_dynamic_defaults.
#
# On success, entrypoint scripts can rely on at least the following variables
# being ready for use:
#   PMRAILS_RUBY_VERSION
#   PMRAILS_IMAGE_REPO
#   PMRAILS_RUBY_VERSION_AT_NEW
#   PMRAILS_PORTS
#   PMRAILS_PROJECT_NAME
#   PMRAILS_DOCKERFILE
#   PMRAILS_COMPOSE_FILE
#
# Globals:
#   PMRAILS_* - Read/Modified. Resolved according to the precedence rules.
#   _PMRAILS_ENV_SNAPSHOT - Modified transiently during setup, then unset.
# Returns:
#   0: On success.
#   Does not return (exits with status 2 or 3): Propagates fatal errors from
#       underlying resolution functions if prerequisites are unmet or parsing
#       fails.
pmrails_setup() {
    pmrails_snapshot_env
    pmrails_load_static_defaults
    pmrails_load_config_files
    pmrails_restore_env
    pmrails_fill_dynamic_defaults
}

# Ensures the in-project HOME directory exists.
#
# Globals:
#   _PMRAILS_VAR_DIR - Read. Parent directory of the HOME directory.
# Returns:
#   0: On success.
#   Non-zero: Propagates the exit status of "mkdir -p" on failure.
pmrails_ensure_home_dir() {
    mkdir -p "${_PMRAILS_VAR_DIR}/home"
}

# Ensures that the container image "<repo>:<version>" exists locally.
#
#   - If PMRAILS_IMAGE_REPO is "ruby", podman is not invoked at all. The
#     upstream ruby image is left to be pulled on demand by a later
#     podman run.
#   - Otherwise, "podman image exists" is queried, and "podman build" is
#     invoked only when the image is missing.
#
# Notes: The build context is the current working directory (".").
#
# Globals:
#   PMRAILS_IMAGE_REPO - Read. Must be set.
#   PMRAILS_RUBY_VERSION - Read. Must be set.
#   PMRAILS_DOCKERFILE - Read. Used as the Dockerfile path for podman build.
#   _PMRAILS_IMAGE_NAME - Modified. Always set to "<repo>:<version>".
# Returns:
#   0: Image exists or was successfully built.
#   Non-zero: Propagates the exit status of "podman build" on failure.
pmrails_ensure_image() {
    _PMRAILS_IMAGE_NAME="${PMRAILS_IMAGE_REPO}:${PMRAILS_RUBY_VERSION}"
    if [ "ruby" != "${PMRAILS_IMAGE_REPO}" ] && ! podman image exists "${_PMRAILS_IMAGE_NAME}"; then
        podman build --build-arg PMRAILS_RUBY_VERSION="${PMRAILS_RUBY_VERSION}" -t "${_PMRAILS_IMAGE_NAME}" -f "${PMRAILS_DOCKERFILE}" .
    fi
}

# Generates a Compose override YAML file for port binding configuration from
# PMRAILS_PORTS.
#
# Writes to the path specified by _PMRAILS_COMPOSE_OVERRIDE_FILE.
#   - If PMRAILS_PORTS is unset, empty, or whitespace-only, writes a minimal
#     "services: {}" placeholder that satisfies Compose validation with no port
#     bindings.
#   - Otherwise: writes a rails-app service block with each whitespace-separated
#     token in PMRAILS_PORTS as a separate port entry, using IFS word splitting.
#     Tokens are passed through unvalidated.
#
# Globals:
#   PMRAILS_PORTS - Read. Whitespace-separated port mappings.
#   _PMRAILS_COMPOSE_OVERRIDE_FILE - Read. The target file path to be
#       created or overwritten.
# Returns:
#   0: Always succeeds.
pmrails_generate_compose_override() {
    (
        set -f
        # shellcheck disable=SC2086
        set -- ${PMRAILS_PORTS:-}
        if [ $# -eq 0 ]; then
            printf 'services: {}\n'
        else
            cat <<'EOF'
services:
  rails-app:
    ports:
EOF
            for port in "$@"; do
                printf '      - "%s"\n' "${port}"
            done
        fi
    ) >"${_PMRAILS_COMPOSE_OVERRIDE_FILE}"
}

# Execs podman-compose with the layered Compose configuration.
#
# Generates the port-binding override file via pmrails_generate_compose_override
# before calling exec, then replaces the current process with podman-compose.
#
# Compose files are applied in the following order (later overrides earlier):
#   1. Built-in base:
#        "$_PMRAILS_SCRIPT_DIR/../share/compose.base.yaml"
#   2. Generated override:
#        "$_PMRAILS_COMPOSE_OVERRIDE_FILE"
#   3. User/project config:
#        "$PMRAILS_COMPOSE_FILE"
#
# Selected variables are injected into podman-compose's environment via "env"
# for use in Compose variable interpolation.
#
# Globals:
#   PMRAILS_RUBY_VERSION - Read. Exported to compose environment.
#   PMRAILS_PROJECT_NAME - Read. Passed to podman-compose via the -p flag.
#   PMRAILS_COMPOSE_FILE - Read. Path to the user/project-specific compose file.
#   _PMRAILS_VAR_DIR - Read. Exported to compose environment.
#   _PMRAILS_IMAGE_NAME - Read. Exported to compose environment.
#   _PMRAILS_SCRIPT_DIR - Read. Used to locate the built-in base compose file.
#   _PMRAILS_COMPOSE_OVERRIDE_FILE - Read. Generated override file path.
# Arguments:
#   $@ - Forwarded verbatim to podman-compose.
# Returns:
#   Does not return: This function exec's podman-compose, replacing the
#       current process.
pmrails_exec_podman_compose() {
    pmrails_generate_compose_override
    exec env \
        PMRAILS_RUBY_VERSION="${PMRAILS_RUBY_VERSION}" \
        _PMRAILS_VAR_DIR="${_PMRAILS_VAR_DIR}" \
        _PMRAILS_IMAGE_NAME="${_PMRAILS_IMAGE_NAME}" \
        podman-compose \
        -p "${PMRAILS_PROJECT_NAME}" \
        -f "${_PMRAILS_SCRIPT_DIR}/../share/compose.base.yaml" \
        -f "${_PMRAILS_COMPOSE_OVERRIDE_FILE}" \
        -f "${PMRAILS_COMPOSE_FILE}" \
        "$@"
}

# Builds podman "-p" arguments from PMRAILS_PORTS.
#
# Parses whitespace-separated tokens in PMRAILS_PORTS, using default IFS
# word splitting, to generate a single string of "-p <token>" arguments
# into _PMRAILS_PORTS_ARGS.
#
# Pathname expansion (globbing) is disabled internally to ensure tokens
# containing wildcard characters (e.g., "*") are treated literally.
#
# If PMRAILS_PORTS is unset or empty, the output is an empty string.
# Tokens are passed through unvalidated. The resulting string is intended
# to be used unquoted in the `podman run` command line.
#
# Globals:
#   PMRAILS_PORTS - Read. Unset or empty produces an empty _PMRAILS_PORTS_ARGS.
#   _PMRAILS_PORTS_ARGS - Written.
# Returns:
#   0: Always succeeds.
pmrails_build_ports_args() {
    _PMRAILS_PORTS_ARGS=$(
        _pmrails_ports_args=""
        _pmrails_port_mapping=""

        set -f
        for _pmrails_port_mapping in ${PMRAILS_PORTS:-}; do
            if [ -n "${_pmrails_ports_args}" ]; then
                _pmrails_ports_args="${_pmrails_ports_args} "
            fi
            _pmrails_ports_args="${_pmrails_ports_args}-p ${_pmrails_port_mapping}"
        done
        printf -- "%s" "${_pmrails_ports_args}"
    )
}

# Returns success when STDOUT is attached to a terminal.
#
# Intended as a small indirection point so callers can share one TTY-detection
# rule and tests can stub that rule without overriding shell builtins.
#
# Returns:
#   0: STDOUT is a TTY.
#   1: STDOUT is not a TTY.
pmrails_stdout_is_tty() {
    [ -t 1 ]
}

# Execs "podman run" with the standard pmrails container layout.
#
# Builds port arguments via pmrails_build_ports_args, checks TTY state
#  (adding -t when so), and replaces the current process with podman.
#
# The container is configured to:
#   - Bind-mount $PWD as /x and use it as the working directory.
#   - Run ephemerally (--rm) and preserve file ownership (--userns=keep-id).
#   - Route HOME, XDG_* directories, and BUNDLE_PATH to the isolated
#     $_PMRAILS_VAR_DIR within /x.
#
# Notes: $_PMRAILS_PORTS_ARGS is expanded unquoted intentionally; it must already
#     be correctly tokenized (produced by pmrails_build_ports_args).
#
# Globals:
#   PMRAILS_PORTS - Read indirectly via pmrails_build_ports_args.
#   _PMRAILS_PORTS_ARGS - Modified by pmrails_build_ports_args, then read.
#   PWD - Read. Used as the bind-mount source.
#   _PMRAILS_VAR_DIR - Read. Base path for runtime directories.
#   _PMRAILS_IMAGE_NAME - Read. Image to run.
# Arguments:
#   $@ - Forwarded verbatim to podman as the container command.
# Returns:
#   Does not return: This function exec's podman, replacing the current
#       process.
pmrails_exec_podman_run() {
    pmrails_build_ports_args
    _tty_flag=""
    if pmrails_stdout_is_tty; then
        _tty_flag="-t"
    fi
    # shellcheck disable=SC2086
    exec podman run -i ${_tty_flag} --rm --userns=keep-id \
        ${_PMRAILS_PORTS_ARGS} \
        -v "${PWD}:/x" -w /x \
        --env "HOME=/x/${_PMRAILS_VAR_DIR}/home" \
        --env "XDG_CACHE_HOME=/x/${_PMRAILS_VAR_DIR}/cache" \
        --env "XDG_CONFIG_HOME=/x/${_PMRAILS_VAR_DIR}/config" \
        --env "XDG_DATA_HOME=/x/${_PMRAILS_VAR_DIR}/share" \
        --env "XDG_STATE_HOME=/x/${_PMRAILS_VAR_DIR}/state" \
        --env "BUNDLE_PATH=/x/${_PMRAILS_VAR_DIR}/bundle" \
        "${_PMRAILS_IMAGE_NAME}" "$@"
}

# Runs "rails new" in a one-shot container to generate a new Rails project.
#
# Checks TTY state (adding -t when so) and runs podman without exec,
# so control returns to the caller after rails new exits.
#
# The function's $1 becomes the rails version (consumed by the inline
# script), and the remaining "$@" are forwarded unchanged to "rails new".
#
# Globals:
#   PMRAILS_RUBY_VERSION_AT_NEW - Read. Selects the upstream ruby image tag.
#   PWD - Read. Used as the bind-mount source.
#   _PMRAILS_ADDITIONAL_ARGS - Read. Optional extra podman flags. Word-split
#       unquoted; values must already be properly tokenized.
# Arguments:
#   $1 - Rails version to install (e.g. "8.0.2").
#   $@ - Remaining arguments forwarded verbatim to "rails new".
# Returns:
#   The exit status of "podman run".
pmrails_podman_run_rails_new() {
    _tty_flag=""
    if pmrails_stdout_is_tty; then
        _tty_flag="-t"
    fi
    # shellcheck disable=SC2086
    podman run -i ${_tty_flag} --rm --userns=keep-id \
        -v "${PWD}:/x" -w /x \
        --tmpfs /home/pmrails --env HOME=/home/pmrails \
        ${_PMRAILS_ADDITIONAL_ARGS:-} \
        ruby:"${PMRAILS_RUBY_VERSION_AT_NEW}" \
        sh -c 'ver="$1"; shift; gem install rails --no-document -v "${ver}" && rails new "$@"' -- "$@"
}
