name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up latest stable Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2

      - name: Install Ruby dependencies
        run: gem install --no-document rake minitest rubocop rubocop-rails-omakase thor activesupport

      - name: Install shell dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y bats bats-assert bats-support shellcheck shfmt

      - name: Run CI
        run: rake ci
